# -*- coding: utf-8 -*-
"""get_vendor _summary.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBx0nvAunB7hVscKc_IOdJLHP4oeIoiv
"""

from google.colab import drive
drive.mount('/content/drive')

import sqlite3
import pandas as pd
import logging
import os
# ---------------- CREATE LOG DIRECTORY ----------------

os.makedirs("logs", exist_ok=True)

db_path = "/content/drive/MyDrive/datas/inventory.db"

try:
    conn = sqlite3.connect(db_path)
    print("Connected to DB")
except Exception as e:
    print("DB connection failed:", e)




# ---------------- SETUP LOGGING ----------------
logging.basicConfig(
    filename='logs/get_vendor_summary.log',
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filemode='a'
)

def create_vendor_summary(conn):
    """Merge tables to produce vendor summary"""
    query = """
    WITH FreightSummary AS (
        SELECT VendorNumber, SUM(Freight) AS freight_cost
        FROM vendor_invoice
        GROUP BY VendorNumber
    ),
    PurchaseSummary AS (
        SELECT
            p.VendorNumber,
            p.VendorName,
            p.Brand,
            p.PurchasePrice,
            p.Description,
            pp.Volume,
            pp.Price AS ActualPrice,
            SUM(p.Quantity) AS TotalPurchaseQuantity,
            SUM(p.Dollars) AS TotalPurchaseDollars
        FROM Purchases p
        JOIN purchase_prices pp
            ON p.Brand = pp.Brand
        WHERE p.PurchasePrice > 0
        GROUP BY
            p.VendorNumber, p.VendorName, p.Brand,
            p.Description, pp.Volume, pp.Price, p.PurchasePrice
    ),
    SalesSummary AS (
        SELECT
            VendorNo,
            VendorName,
            Brand,
            SUM(SalesQuantity) AS TotalSalesQuantity,
            SUM(SalesDollars) AS TotalSalesDollars,
            SUM(ExciseTax) AS TotalExciseTax,
            SUM(SalesPrice) AS TotalSalesPrice
        FROM sales
        GROUP BY VendorNo, Brand
    )

    SELECT
        ps.*,
        ss.TotalSalesQuantity,
        ss.TotalSalesDollars,
        ss.TotalExciseTax,
        ss.TotalSalesPrice,
        fs.freight_cost
    FROM PurchaseSummary ps
    LEFT JOIN SalesSummary ss
        ON ps.VendorNumber = ss.VendorNo
        AND ps.Brand = ss.Brand
    LEFT JOIN FreightSummary fs
        ON ps.VendorNumber = fs.VendorNumber
    ORDER BY TotalPurchaseDollars DESC
    """
    return pd.read_sql(query, conn)

def clean_data(df):
    """Clean and add new computed columns"""

    df['Volume'] = df['Volume'].astype(float)
    df['PurchasePrice'] = df['PurchasePrice'].astype(float)

    df.fillna(0, inplace=True)

    df['VendorName'] = df['VendorName'].str.strip()
    df['Description'] = df['Description'].str.strip()

    df['GrossProfit'] = df['TotalSalesDollars'] - df['TotalPurchaseDollars']
    df['ProfitMargin'] = (df['GrossProfit'] / df['TotalPurchaseDollars']) * 100
    df['StockTurnover'] = df['TotalSalesQuantity'] / df['TotalPurchaseQuantity']
    df['SalesToPurchaseRatio'] = df['TotalSalesDollars'] / df['TotalPurchaseDollars']

    return df

if __name__ == '__main__':

    conn = sqlite3.connect('/content/drive/MyDrive/datas/inventory.db')

    logging.info("Creating vendor summary...")
    vendor_sales_summary = create_vendor_summary(conn)
    logging.info(vendor_sales_summary.head())

    logging.info("Cleaning data...")
    clean_df = clean_data(vendor_sales_summary)
    logging.info(clean_df.head())

    logging.info("Completed successfully.")

